spring:
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

logging:
  level:
    org.springframework: INFO
    com.zaxxer.hikari: DEBUG
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure: 
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

---
spring:
  profiles: docker
  datasource:
    username: system
    password: oracle
    url: jdbc:oracle:thin:@//localhost:1521/xe
  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
  main:
    allow-bean-definition-overriding: true

---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true