logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure: 
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

---
spring:
  profiles: docker
  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration

---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true